# Generated by Django 4.2.2 on 2023-06-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniveristyCampus',
            new_name='UniversityCampus',
        ),
    ]
