# Generated by Django 4.2.2 on 2023-06-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0002_rename_univeristycampus_universitycampus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycampus',
            old_name='campus_id',
            new_name='campus_Id',
        ),
    ]
